// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.2
// LVGL version: 9.1.0
// Project name: Mini_Clock

#include "ui.h"

void ui_Screen1_screen_init(void)
{
ui_Screen1 = lv_obj_create(NULL);
lv_obj_remove_flag( ui_Screen1, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Screen1, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Screen1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TimeLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TimeLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TimeLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TimeLabel, 0 );
lv_obj_set_y( ui_TimeLabel, 20 );
lv_obj_set_align( ui_TimeLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TimeLabel,"Dev91 Studio");
lv_obj_set_style_text_color(ui_TimeLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TimeLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TimeLabel, &lv_font_montserrat_30, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_TempLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_TempLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_TempLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_TempLabel, -50 );
lv_obj_set_y( ui_TempLabel, 70 );
lv_obj_set_align( ui_TempLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_TempLabel,"Temp");
lv_obj_set_style_text_color(ui_TempLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_TempLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_TempLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_HumiLabel = lv_label_create(ui_Screen1);
lv_obj_set_width( ui_HumiLabel, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_HumiLabel, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_HumiLabel, 50 );
lv_obj_set_y( ui_HumiLabel, 70 );
lv_obj_set_align( ui_HumiLabel, LV_ALIGN_CENTER );
lv_label_set_text(ui_HumiLabel,"Humi");
lv_obj_set_style_text_color(ui_HumiLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_HumiLabel, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_HumiLabel, &lv_font_montserrat_20, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Image3 = lv_image_create(ui_Screen1);
lv_image_set_src(ui_Image3, &ui_img_1204119307);
lv_obj_set_width( ui_Image3, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Image3, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Image3, 0 );
lv_obj_set_y( ui_Image3, -55 );
lv_obj_set_align( ui_Image3, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Image3, LV_OBJ_FLAG_CLICKABLE );   /// Flags
lv_obj_remove_flag( ui_Image3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

}
